### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by sebsobseb** [maslakoff/php-etherscan-api#2]
Is it possible?

**Comment by maslakoff** [comment]
Hi @sebsobseb . Will be enough to add a ^8.0 to a composer.json?

**Comment by sebsobseb** [comment]
I think so, yeah. 
But, maybe quickly go through the breaking changes, to see if it could break? https://www.php.net/manual/en/migration80.incompatible.php

**Comment by maslakoff** [comment]
@sebsobseb composer.json was updated.
